import { motion, useReducedMotion, useScroll, useTransform } from "motion/react";
import { Link } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import heroBike from "@/assets/hero-superbike.jpg";
import engineDetail from "@/assets/engine-detail.jpg";
import { features } from "./data";
import { ActionLink, Reveal } from "./ui";

const words=["POWER","PERFORMANCE","PRECISION","SPEED","RELIABILITY"];
function RotatingWord(){const [i,setI]=useState(0);useEffect(()=>{const t=setInterval(()=>setI(v=>(v+1)%words.length),2200);return()=>clearInterval(t)},[]);return <div className="rotating-word"><motion.span key={words[i]} initial={{opacity:0,y:18,filter:"blur(10px)"}} animate={{opacity:1,y:0,filter:"blur(0px)"}} exit={{opacity:0}} transition={{duration:.65}}>{words[i]}</motion.span></div>}
function Counter({target,suffix=""}:{target:number;suffix?:string}){const [n,setN]=useState(0);const ref=useRef<HTMLSpanElement>(null);useEffect(()=>{let frame=0;const start=performance.now();const run=(now:number)=>{const p=Math.min((now-start)/1100,1);setN(Math.round(target*(1-Math.pow(1-p,3))));if(p<1)frame=requestAnimationFrame(run)};frame=requestAnimationFrame(run);return()=>cancelAnimationFrame(frame)},[target]);return <span ref={ref}>{n.toLocaleString()}{suffix}</span>}
export function HomePage(){const reduce=useReducedMotion();const {scrollY}=useScroll();const imageY=useTransform(scrollY,[0,700],[0,reduce?0:70]);return <>
<section className="hero section-shell"><motion.img src={heroBike} alt="Black premium sports motorcycle in a blue-lit studio" width={1920} height={1088} className="hero-image" style={{y:imageY}}/><div className="hero-shade"/><div className="hero-content"><motion.p className="eyebrow" initial={{opacity:0,y:14}} animate={{opacity:1,y:0}}>RIDE SMARTER. MAINTAIN BETTER.</motion.p><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.08}}><span>BUILT FOR</span><RotatingWord/></motion.h1><motion.div className="hero-actions" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.22}}><ActionLink to="/tracker">Get started</ActionLink><ActionLink to="/tracker" variant="outline">Track my bike</ActionLink></motion.div></div><div className="hero-telemetry"><span>ENGINE / 998 CC</span><span>STATUS / READY</span><span>REV / 14.5K</span></div></section>
<section className="section-shell metrics-grid"><div><small>RIDERS ON GRID</small><strong><Counter target={24800} suffix="+"/></strong><span>ACTIVE GARAGES</span></div><div><small>DISTANCE LOGGED</small><strong><Counter target={12} suffix="M"/></strong><span>KILOMETRES</span></div><div><small>ON-TIME SERVICE</small><strong><Counter target={99} suffix="%"/></strong><span>NETWORK RATE</span></div><div><small>PARTNER WORKSHOPS</small><strong><Counter target={310} suffix="+"/></strong><span>NATIONWIDE</span></div></section>
<section className="section-shell section-block"><Reveal className="section-heading"><div><p className="eyebrow">(A) MAINTENANCE SYSTEM</p><h2>Every bolt, on record.</h2></div><span>SIX CORE MODULES</span></Reveal><div className="feature-grid">{features.map((f,i)=><Reveal key={f.title} className="feature-card"><div className="feature-top"><span>0{i+1}</span><f.icon/></div><h3>{f.title}</h3><p>{f.copy}</p></Reveal>)}</div></section>
<section className="section-shell editorial-grid"><Reveal className="editorial-image"><img src={engineDetail} alt="Precision motorcycle engine components" loading="lazy" width={1200} height={912}/></Reveal><Reveal className="editorial-copy"><p className="eyebrow">(B) MACHINE INTELLIGENCE</p><h2>Signals before symptoms.</h2><p>Veloce turns routine logs into a clear mechanical picture. Every ride updates service intervals, component wear and cost forecasts.</p><ul><li><CheckCircle2/>Mileage-aware schedules</li><li><CheckCircle2/>Document and insurance alerts</li><li><CheckCircle2/>Service cost intelligence</li></ul><Link to="/tracker" className="text-link">Open the cockpit <ArrowRight/></Link></Reveal></section>
<section className="section-shell section-block"><Reveal className="section-heading"><div><p className="eyebrow">(C) LIVE OVERVIEW</p><h2>Your garage, instrumented.</h2></div><Link to="/tracker" className="text-link">Full dashboard <ArrowRight/></Link></Reveal><DashboardPreview/></section>
<section className="section-shell closing-cta"><Reveal><p className="eyebrow">READY TO ROLL</p><h2>Put your bike on the grid.</h2><div className="hero-actions"><ActionLink to="/tracker">Get started</ActionLink><ActionLink to="/contact" variant="outline">Talk to us</ActionLink></div></Reveal></section></>}
function DashboardPreview(){return <Reveal className="dash-preview"><div className="window-bar"><span/><span/><span/><small>DASHBOARD / OVERVIEW</small></div><div className="preview-grid"><div className="health-panel"><small>ENGINE HEALTH</small><div className="gauge"><div><strong>98</strong><span>RATED</span></div></div><p>All systems nominal</p></div><div><small>SERVICE QUEUE</small><ul className="queue"><li><span>Oil & filter</span><b>IN 420 KM</b></li><li><span>Chain tension</span><b>DUE NOW</b></li><li><span>Brake fluid</span><em>IN 1,900 KM</em></li><li><span>Tyre inspection</span><em>IN 3,100 KM</em></li></ul></div><div><small>ODOMETER · 30 DAYS</small><div className="bar-chart">{[40,58,48,72,60,88,100].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="chart-labels"><span>W1</span><span>W2</span><span>W3</span><span>W4</span></div></div></div></Reveal>}
