import { useMemo, useRef, useState } from "react";
import { Bike, FileText, Plus, Upload, X } from "lucide-react";
import { Button, Reveal } from "./ui";

type Service={name:string,date:string,km:string,cost:string};
const initial=[{name:"Full service",date:"12 Sep 2026",km:"12,180 km",cost:"₹8,400"},{name:"Rear tyre replacement",date:"04 Jul 2026",km:"10,940 km",cost:"₹12,900"},{name:"Battery diagnostic",date:"21 Apr 2026",km:"9,860 km",cost:"₹1,250"}];
export function TrackerDashboard(){const [mileage,setMileage]=useState(12840);const [bike,setBike]=useState("Kawasaki Ninja ZX-6R");const [services,setServices]=useState<Service[]>(initial);const [modal,setModal]=useState<"bike"|"service"|null>(null);const [uploaded,setUploaded]=useState<string[]>(["insurance-2026.pdf","service-invoice-0912.pdf"]);const file=useRef<HTMLInputElement>(null);const health=Math.max(72,98-Math.floor((mileage-12840)/250));const bars=useMemo(()=>[42,64,52,80,61,91,Math.min(100,55+(mileage%900)/20)],[mileage]);
return <div className="section-shell tracker-layout"><div className="tracker-toolbar"><div><p className="eyebrow">LIVE GARAGE / 01</p><h2>{bike}</h2><span>2024 · Petrol · Active</span></div><div className="toolbar-actions"><Button variant="outline" onClick={()=>setModal("service")}><Plus/> Log service</Button><Button onClick={()=>setModal("bike")}><Bike/> Add bike</Button></div></div>
<div className="progress-grid"><article><small>ODOMETER</small><strong>{mileage.toLocaleString()} <em>KM</em></strong><label htmlFor="mileage">UPDATE READING</label><input id="mileage" type="range" min="12840" max="18000" value={mileage} onChange={e=>setMileage(Number(e.target.value))}/></article><article><small>ENGINE HEALTH</small><div className="mini-gauge"><strong>{health}</strong><span>RATED</span></div></article><article><small>NEXT SERVICE</small><strong>{Math.max(0,15000-mileage).toLocaleString()} <em>KM</em></strong><p>Oil, filter & system inspection</p></article><article><small>YEARLY SPEND</small><strong>₹32,480</strong><p>8% below similar bikes</p></article></div>
<div className="dashboard-grid"><Reveal className="chart-panel panel"><div className="panel-title"><div><small>RIDING LOAD</small><h3>Weekly kilometres</h3></div><span>LAST 7 WEEKS</span></div><div className="large-chart">{bars.map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>W{i+1}</span></div>)}</div></Reveal><Reveal className="panel reminders"><div className="panel-title"><div><small>UPCOMING</small><h3>Maintenance queue</h3></div></div><ul><li><i/><div><b>Chain tension</b><span>Due now</span></div><strong>URGENT</strong></li><li><i/><div><b>Oil & filter</b><span>In {Math.max(0,15000-mileage)} km</span></div><strong>SOON</strong></li><li><i/><div><b>Insurance renewal</b><span>18 Nov 2026</span></div><em>57 DAYS</em></li></ul></Reveal></div>
<div className="dashboard-grid bottom"><Reveal className="panel"><div className="panel-title"><div><small>HISTORY</small><h3>Maintenance records</h3></div><Button variant="quiet" onClick={()=>setModal("service")}><Plus/> Add</Button></div><div className="records">{services.map(s=><div key={s.name+s.date}><FileText/><span><b>{s.name}</b><small>{s.date} · {s.km}</small></span><strong>{s.cost}</strong></div>)}</div></Reveal><Reveal className="panel"><div className="panel-title"><div><small>VAULT</small><h3>Uploaded records</h3></div><Button variant="quiet" onClick={()=>file.current?.click()}><Upload/> Upload</Button><input ref={file} hidden type="file" onChange={e=>{const f=e.target.files?.[0];if(f)setUploaded(v=>[f.name,...v])}}/></div><div className="records">{uploaded.map(name=><div key={name}><FileText/><span><b>{name}</b><small>Secured document</small></span><Button variant="quiet" aria-label={`Remove ${name}`} onClick={()=>setUploaded(v=>v.filter(x=>x!==name))}><X/></Button></div>)}</div></Reveal></div>
{modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(null)}><form className="modal" onSubmit={e=>{e.preventDefault();if(modal==="service")setServices(v=>[{name:"Workshop inspection",date:"24 Sep 2026",km:`${mileage.toLocaleString()} km`,cost:"₹2,400"},...v]);else setBike("Ducati Monster 937");setModal(null)}} onMouseDown={e=>e.stopPropagation()}><Button type="button" variant="quiet" className="modal-close" onClick={()=>setModal(null)}><X/></Button><p className="eyebrow">{modal==="bike"?"NEW MACHINE":"NEW RECORD"}</p><h3>{modal==="bike"?"Add a bike":"Log maintenance"}</h3><label>{modal==="bike"?"Bike name":"Service type"}<input defaultValue={modal==="bike"?"Ducati Monster 937":"Workshop inspection"}/></label><label>{modal==="bike"?"Model year":"Service cost"}<input defaultValue={modal==="bike"?"2026":"₹2,400"}/></label><Button type="submit">Save record</Button></form></div>}</div>}
